/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CircleProgressBar: typeof import('./src/components/CircleProgressBar/index.vue')['default']
    ProgressLineBar: typeof import('./src/components/ProgressLineBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Student: typeof import('./src/components/Student/index.vue')['default']
  }
}
